export { default as FacebookIcon } from "./Icon/FacebookIcon"
export { default as HomeTabIcon } from "../svg/Icon/HomeTabIcon"
export { default as OrderTabIcon } from "../svg/Icon/OrdersTabIcon"
export { default as SearchTabIcon } from "../svg/Icon/SearchTabIcon"
export { default as ProfileTabIcon } from "../svg/Icon/ProfileTabIcon"
export { default as GoogleIcon } from "../svg/Icon/GoogleIcon"
export { default as PasswordVisibleIcon } from "../svg/Icon/PasswordInvisibleIcon"
export { default as dotIcon } from "../svg/Icon/DotsIcon"
export { default as DollarIcon } from "../svg/Icon/DollarIcon"
export { default as TimeIcon } from "../svg/Icon/TimeIcon"
export { default as StarIcon } from "../svg/Icon/StarIcon"
export { default as ClockIcon } from "../svg/Icon/ClockIcon"
export { default as SearchIcon } from "../svg/Icon/SearchIcon"
export { default as BackIcon } from "../svg/Icon/BackIcon"
export { default as LockIcon } from "../svg/Icon/LockIcon"
export { default as LocationTabIcon } from "../svg/Icon/LocationtabIcon"
export { default as PaymentIcon } from "../svg/Icon/PaymentIcon"
export { default as ShareIcon } from "../svg/Icon/ShareIcon"
export { default as LogoutIcon } from "../svg/Icon/LogoutIcon"
export { default as NotificationIcon } from "../svg/Icon/NotificationIcon"
export { default as NoteBook } from "../svg/Icon/NoteBook"
export { default as ShareArrowIcon } from "../svg/Icon/ShareArrowIcon"
export { default as SendIcon } from "../svg/Icon/SendIcon"



