import { Profiler } from "react";

export enum Routes {
    MAIN = 'Main',
    ONBOARDING = 'Onboarding',
    AUTHORIZATIONNAVIGATION = 'AuthorizationNavigation',
    Authorization = 'Authorization',
    LOGIN = "Sign In",
    REGISTER = "Sign up",
    VERIFYNUMBER = "Verify",
    FORGOTPASSWORD = "Forgot Password",
    RESETEMAIL = "Reset Email",
    GETSTARTED = "Get Started",
    HOME = "Home",
    SEARCH = "Search",
    ORDERS = "Orders",
    Profile = "Profile",
    FeaturePartner = "Feature Partner",
    AllRestaurants = "All Restaurants",
    HomeNavigation = "Home navigation",
    HomeScreen = "Home Screen",
    RestaurantDetail = " Restaurants Detail",
    AddToOrder = "Add to Order",
    RestaurantsSearch = "Restaurants Search",
    RestaurantCategorySearch = "Restaurants Categories Search",
    searchFoodItems = "Search Food Items",
    AccountSettings = "Account Settings",
    ChangeProfileSetting = "Change Profile Settings",
    ChangePasswordSetting = "Change Password Settings",
    AddPaymentMethods = "Add Payment Methods",
    PaymentMethod = "Payment Method",
    AddSocialAccount = "Add Social Account",
    ReferToFriend = "Refer To Friend",
    StoreLocation = "Store Location",
}