
const images = {
    sliderImage: require('./sliderimage.png'),
    introslider1Image: require('./introslider1image.png'),
    introslider2Image: require('./intoslider2image.png'),
    introslider3Image: require('./introslider3image.png'),
    introslider4Image: require('./introslider4image.png'),
    resetEmailPageImage: require('./resetEmailImage.png'),
    homePageSlider1: require("./22-fast-food-9-20wsq.webp"),
    homePageSlider2: require("./360_F_228281605_zX4rGhhAX6fNkBgx7dp1IXu8XMnhCl01.jpg"),
    homePageSlider3: require("./Bitmap.png"),
    homePageSlider4: require("./images.png"),
    homePageSlider5: require("./istockphoto-1457979959-170667a.webp"),
    homePageSlider6: require("./grilled-gourmet-burger-rustic-table-ready-eat-with-fries-generated-by-artificial-intelligence_25030-63055.png"),
    homePageSlider7: require("./offers1.jpg"),

    homeScreenBanner: require("./Banner.png"),
    Restaurants1: require("./restraunts13.png"),
    Restaurants2: require("./restraunts12.png"),
    Restaurants3: require("./restraunts11.png"),
    Restaurants4: require("./restraurant10.png"),
    Restaurants5: require("./restraunts9.png"),
    Restaurants6: require("./restaurants8.png"),
    Restaurants7: require("./restaurants7.png"),
    Restaurants8: require("./Restaurant_Näsinneula.jpg"),
    Restaurants9: require("./restrautnsImage6.png"),
    Restaurants10: require("./pexels-igor-starkov-1307698.jpg"),
    Restaurants11: require("./allrestrauntsimagee5.png"),
    Restaurants12: require("./restrauntsImage4.png"),
    Restaurants13: require("./restaurants14.jpg"),
    mostPopularlFood1: require("./mostPopularFood1.png"),
    mostPopularlFood2: require("./mostPopularFood2.png"),
    mostPopularlFood3: require("./mostPopularFood3.png"),
    mostPopularlFood4: require("./mostPopularFood4.png"),
    mostPopularlFood5: require("./mostPopularFood5.png"),
    AppetizersImage9: require("./AppetizersImage9.png"),
    TopRestaurants1: require("./TopRestaurants1.png"),
    TopRestaurants2: require("./TopRestaurants2.png"),
    TopRestaurants3: require("./TopRestaurants3.png"),
    TopRestaurants4: require("./TopRestaurants4.png"),
    TopRestaurants5: require("./TopRestaurants5.png"),
    PaymentCardImage: require("./Icon-CreditCard.png"),
    PaypalImage: require("./paypalImage.png"),
    MasterCardImage: require("./masterCard.png"),
    VisaCardImage: require("./VisaCardImage.png"),
    cameraImage: require("./cameraImage.png"),

}

export default images

